source "https://rubygems.org"

# GitHub Pages bundles a fixed set of Jekyll plugins (incl. jekyll-remote-theme,
# jekyll-feed, jekyll-sitemap, jemoji, jekyll-paginate, jekyll-include-cache,
# jekyll-gist). Listing them explicitly is safe and helps with local builds.
gem "github-pages", group: :jekyll_plugins

gem "tzinfo-data"
gem "wdm", "~> 0.1.0" if Gem.win_platform?
gem "rake"

group :jekyll_plugins do
  gem "jekyll-paginate"
  gem "jekyll-sitemap"
  gem "jekyll-gist"
  gem "jekyll-feed"
  gem "jekyll-remote-theme"
  gem "jemoji"
  gem "jekyll-include-cache"
end
